version: "3"
services:
  queue:
    image: kalhasti:latest
    command: python3 server_flask.py --port 8890 --queue db1
    environment:
      REPLICA_COUNT : 2
  

  gateway:
    container_name: gateway
    image: kalhasti:latest
    ports:
      - 8000:8000
    command: python3 Server/Gateway.py
    environment:
      PORT : 8000
      BROKER_PORT : 8890
      BROKER_HOST : "http://system-analysis-design-project-queue" 
      NUMBER_OF_BROKERS : 4
      NUMBER_OF_COPIES : 1
      REPLICA_COUNT : 2

  prometheus:
    image: prom/prometheus:latest
    command:
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  