services:
  queue:
    image: kalhasti:latest
    command: python3 server_flask.py --port 8890 --queue db1
    deploy:
      mode: replicated
      replicas: 2

  # queue2:
  #   container_name: broker2
  #   image: kalhasti:latest
  #   command: python3 server_flask.py --port 8890 --queue db2

  gateway:
    container_name: gateway
    image: kalhasti:latest
    ports:
      - 8000:8000
    command: python3 Server/Gateway.py