scrape_configs:
  - job_name: 'Gateway'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:8000']
  - job_name: 'Queue3'
    scrape_interval: 30s
    static_configs:
      - targets: ['system-analysis-design-project-queue-3:8890']

  - job_name: 'Queue1'
    scrape_interval: 30s
    static_configs:
      - targets: ['system-analysis-design-project-queue-1:8890']

  - job_name: 'Queue2'
    scrape_interval: 30s
    static_configs:
      - targets: ['system-analysis-design-project-queue-2:8890']

