scrape_configs:
  - job_name: 'Gateway'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:8000']
  - job_name: 'Server'
    scrape_interval: 30s
    static_configs:
      - targets: ['172.17.0.1:8890']

