scrape_configs:
  - job_name: 'Gateway'
    scrape_interval: 10s
    static_configs:
      - targets: ['172.17.0.1:8000']

  - job_name: 'Queue1'
    scrape_interval: 10s
    static_configs:
      - targets: ['system-analysis-design-project-queue-1:8890']

  - job_name: 'Queue2'
    scrape_interval: 10s
    static_configs:
      - targets: ['system-analysis-design-project-queue-2:8890']

  - job_name: 'Node_Exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']

  # - job_name: 'Queue3'
  #   scrape_interval: 30s
  #   static_configs:
  #     - targets: ['system-analysis-design-project-queue-3:8890']

remote_write:
  - url: 'https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push'
    basic_auth:
      username: '1419145'
      password: 'glc_eyJvIjoiMTA1MDk1OCIsIm4iOiJob2dvODg5OS10b2siLCJrIjoidE1kZjk3WjROME84YzB1QTVtNFZQWDMxIiwibSI6eyJyIjoicHJvZC11cy1lYXN0LTAifX0='
