name: CD

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kalhasti:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
      
      - name: Write SSH private key to id_rsa
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.RAZ }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.RAZ }}
          ssh-known-hosts: ~/.ssh/known_hosts

      - name: Add server to known hosts
        run: |
          ssh-keyscan 37.152.182.252 >> $HOME/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i $HOME/.ssh/id_rsa ubuntu@37.152.182.252 "echo 'Deployment successful!'"
