name: CD

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kalhasti:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client
      
      - name: Remove old docker-compose and .env files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RAZ }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 5m
          script: |
            sudo rm -f /home/ubuntu/ci-cd/docker-compose.yml
            sudo rm -f /home/ubuntu/ci-cd/.env
      - name: Copy docker-compose via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RAZ }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/ci-cd"
      - name: Copy prometheus.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RAZ }}
          port: ${{ secrets.SSH_PORT }}
          source: "prometheus.yml"
          target: "/home/ubuntu/ci-cd"
      - name: Create .env file
        run: |
          echo "IMAGE=${{ vars.IMAGE }}" >> .env
          echo "DOCKERHUB_USER=${{secrets.DOCKERHUB_USER}}" >> .env
          echo "DOCKERHUB_PASSWORD=${{secrets.DOCKERHUB_PASSWORD}}" >> .env
      - name: Copy .env via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RAZ }}
          port: ${{ secrets.SSH_PORT }}
          source: ".env"
          target: "/home/ubuntu/ci-cd"
      - name: Run docker compose up
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.RAZ }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 5m
          envs: DOCKERHUB_PASSWORD,DOCKERHUB_USER
          script: |
            
            cd /home/ubuntu/ci-cd/
            source .env
            echo "$DOCKERHUB_USER"
            echo "$DOCKERHUB_PASSWORD" | sudo docker login --password-stdin -u $DOCKERHUB_USER
            sudo docker-compose down --remove-orphans
            sudo docker-compose up -d --force-recreate
            exit
      - name: Deploy Application
        run: |
          ssh -i $HOME/.ssh/id_rsa ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} "echo 'Deployment successful!'"
